title: Hetic X.1000 is a program for automating routine tasks.
description: The Hetic X.1000 program will be able to record and repeat everything you do on the computer manually.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
github:
  zip_url: http://example.com/download.zip
  another_url: another value
